class Constants:
    RATE_AUDIO = 160
    TEXT_CHAT = 14
    TIPE_DOWNLOAD_CHAT = 'Zip'
    ASPECT_GRID = 1.00
    INDEX_CHAT_RAIL = 'INDEX_CHAT_RAIL'
    INDEX_DOWNLOAD_RAIL = 'INDEX_DOWNLOAD_RAIL'
    SEND_USER = 'user'
    SEND_BOT = 'assistant'
    RATE_PREFERENCE = 'RATE_PREFERENCE'
    TEXT_CHAT_PREFERENCE = 'TEXT_CHAT_PREFERENCE'
    PATH_SAVE_CHAT = 'PATH_SAVE_CHAT'
    TYPE_SAVE_FILE = 'TYPE_SAVE_FILE'
    PATH_DOWNLOAD_DB = 'PATH_DOWNLOAD_DB'
    VIDEO_LIST = 'VIDEO_LIST'
    TIPE_DOWNLOAD_QUALITY = 'Alta'
    PATH_DOWNLOAD_VIDEOS = 'PATH_DOWNLOAD_VIDEOS'
    DOWNLOAD_TYPE_SAVE_FILE = 'DOWNLOAD_TYPE_SAVE_FILE'
    COUNTER_STATE = 'COUNTER_STATE'

    LONGITUD_GENERATOR = "LONGITUD_GENERATOR"
    TERMINACION_GENERATOR = "TERMINACION_GENERATOR"
    RESULTADOS_GENERATOR = "RESULTADOS_GENERATOR"
    CONTAINER_GENERATOR = 'CONTAINER_GENERATOR'
